## Pandas

In [ ]:
# 1. pandas is used to manipulate the data.

# Ex. Read data from different sources, extract information, filter rows, filter columns, group data, 
#     replace missing values, replace values etc etc.

In [ ]:
# import libraries 

import numpy as nm
import pandas as pd

In [ ]:
# 1. Read Data from different sources

# pd.read_csv(" ") : reading the data from a  .csv file
# pd.read_excel(" ") : reading the data from a .xlsx file
# pd.read_sql(" ")  : reading the data from .sql file
# pd.read_json(" ") : reading the data from json file
# pd.read_html(" ") : reading the data from html file

In [ ]:
# 1-D : Series()
# 2-D : DataFrame()
# 3-D : Panel
# 4-D : Panel4 D

### Series

In [ ]:
a = [10, 20, 30, 40, 50]
print(a, type(a))

[10, 20, 30, 40, 50] <class 'list'>


In [ ]:
arr1 = nm.array(a)
print(arr1, type(arr1))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [ ]:
s1 = pd.Series(a)
print(s1, type(s1))

0    10
1    20
2    30
3    40
4    50
dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
# In pandas default index of Series starts from 0.
# In Series we can change index values.

In [ ]:
# changing Index

In [ ]:
s2 = pd.Series(a,index = ['a', 'b', 'c', 'd', 'e'] )

print(s2)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [ ]:
s3 = pd.Series(a, index = [0,2,4,6,8])

print(s3)

0    10
2    20
4    30
6    40
8    50
dtype: int64


In [ ]:
## Accessing Elements : index

# s1 : Display 30, 50

s1[2], s1[4]

(30, 50)

In [ ]:
# s2 : 30, 50

print(s2[2], s2[4])
print(s2['c'], s2['e'])

# Elements can be accessed with both default and new indices.

30 50
30 50


In [ ]:
# s3 : 30, 50

#print(s3[1], s3[3])
print(s3[4], s3[8])

# In case of conflicting indices new index values will prevail.

30 50


In [ ]:
# 2. Slicing : series_name[start  : end : steps ]

In [ ]:
# Display 10,20,30

print(s1[0 :3 ])

0    10
1    20
2    30
dtype: int64


In [ ]:
# Display 40,50

print(s1[3:5])

3    40
4    50
dtype: int64


In [ ]:
# Display 10,30,50

print(s1[ : : 2])

0    10
2    30
4    50
dtype: int64


In [ ]:
# Create Marks of 20 students out of 100 and convert it into series. [40 to 98]

m = nm.random.randint(40, 98, 20)
print(m, type(m))

[93 74 69 80 79 96 73 57 81 46 68 49 72 69 67 56 56 53 63 69] <class 'numpy.ndarray'>


In [ ]:
s5 = pd.Series(m)
print(s5)

0     93
1     74
2     69
3     80
4     79
5     96
6     73
7     57
8     81
9     46
10    68
11    49
12    72
13    69
14    67
15    56
16    56
17    53
18    63
19    69
dtype: int32


In [ ]:
# Slicing :

# Display marks of first 5 students.

print(s5[ :5 ])

0    93
1    74
2    69
3    80
4    79
dtype: int32


In [ ]:
# Display marks of last 5 students
print(s5[-5 :])

15    56
16    56
17    53
18    63
19    69
dtype: int32


In [ ]:
# Display marks of alternate students.
print(s5[ : : 2])

0     93
2     69
4     79
6     73
8     81
10    68
12    72
14    67
16    56
18    63
dtype: int32


In [ ]:
# Display marks of every 3rd student from 5 to 15.
print(s5[ 4: 15: 3])

4     79
7     57
10    68
13    69
dtype: int32


In [ ]:
# sum, min, max, mean, median

print(" Sum of all Marks ", s5.sum())
print(" Min Value of all Marks ", s5.min())
print(" Max Value of all Marks ", s5.max())
print(" Mean of  Marks ", s5.mean())
print(" Median o Marks ", s5.median())

 Sum of all Marks  1370
 Min Value of all Marks  46
 Max Value of all Marks  96
 Mean of  Marks  68.5
 Median o Marks  69.0


In [ ]:
# Python : Sequences : List, Dictionary

In [ ]:
# Let us create a series with Dictionary.

d1 = { 'ID' : 1011, 'Name' : 'ABC', 'Sal': 56780, 'Mob' : True }

print(d1, type(d1))

{'ID': 1011, 'Name': 'ABC', 'Sal': 56780, 'Mob': True} <class 'dict'>


In [ ]:
s6 = pd.Series(d1)

print(s6, type(s6))

ID       1011
Name      ABC
Sal     56780
Mob      True
dtype: object <class 'pandas.core.series.Series'>


In [ ]:
s6['Name'], s6['Sal']

('ABC', 56780)

In [ ]:
# Attributes : 

In [ ]:
# 1. index

print(" Indices of S1 : ", list(s1.index))
print(" Indices of S2 : ", list(s2.index))
print(" Indices of S3 : ", list(s3.index))
#print(" Indices of S4 : ", list(s4.index))
print(" Indices of S5 : ", list(s5.index))
print(" Indices of S6 : ", list(s6.index))

 Indices of S1 :  [0, 1, 2, 3, 4]
 Indices of S2 :  ['a', 'b', 'c', 'd', 'e']
 Indices of S3 :  [0, 2, 4, 6, 8]
 Indices of S5 :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
 Indices of S6 :  ['ID', 'Name', 'Sal', 'Mob']


In [ ]:
# 2. values

print(s1.values)
print(s2.values)
print(s5.values)
print(s6.values)

[10 20 30 40 50]
[10 20 30 40 50]
[93 74 69 80 79 96 73 57 81 46 68 49 72 69 67 56 56 53 63 69]
[1011 'ABC' 56780 True]


In [ ]:
# 3. shape 

print(s1.shape)
print(s5.shape)
print(s6.shape)

(5,)
(20,)
(4,)


In [ ]:
# 4. size 

print(s1.size)
print(s5.size)
print(s6.size)

5
20
4


In [ ]:
# 5. ndim

print(s1.ndim)
print(s5.ndim)
print(s6.ndim)

1
1
1


In [ ]:
# 6. check for missing values : empty

print(s1.empty)
print(s5.empty)
print(s6.empty)

False
False
False


In [ ]:
s7 = s1 + s5

In [ ]:
print(s7.empty)

False


In [ ]:
# isna()

s7.isna()

15

In [ ]:
s7.isna().sum()    # to count 'nan' values

In [ ]:
# head() : Display first 5 rows with header

s7.head() 

0    103.0
1     94.0
2     99.0
3    120.0
4    129.0
dtype: float64

In [ ]:
# tail() : Display last 5 rows with header

s5.tail()

15    56
16    56
17    53
18    63
19    69
dtype: int32

In [ ]:
# sample() : a random row with header

s5.sample(3)

18    63
17    53
13    69
dtype: int32

In [ ]:
nm.dtype("r", nm.dtype , 1 )

TypeError: data type 'r' not understood