##Numpy

In [1]:
# Numpy : 

# SEQUENCE => ARRAY()
# 1D, 2D, 3D
# ACCESS THE ELEMENTS : INDEX AND SLICING
# ATTRIBUTES : NDIM, SHAPE, SIZE ETC
# FUNCTIONS : SUM() MIN() MAX()   : ROWS : 1  COLUMNS : 0
# FUNCTION : RESHAPE()

# range() arange() linspace()
# Random Number Generator
# Trigonometric Funcrions : sin(), cos(), tan()
# Statistical Function : mean(), median()
# decimal function : ceil(), floor(), around()

In [2]:
# Sequences :
# 1. List
# 2. Tuples 
# 3. Dictionary
# 4. Sets
# 5. String

In [ ]:
# List : It is collection of items.

a = [10, 20, 30, 40, 50]
b = [.1, .2, .3, .4, .5]

print(a+b)

[10, 20, 30, 40, 50, 0.1, 0.2, 0.3, 0.4, 0.5]


In [ ]:
# import the library

import numpy as nm

In [ ]:
a = [10, 20, 30, 40, 50]
b = [.1, .2, .3, .4, .5]
#    0    1   2   3   4          
print(a, type(a))
print(b, type(b))

[10, 20, 30, 40, 50] <class 'list'>
[0.1, 0.2, 0.3, 0.4, 0.5] <class 'list'>


In [ ]:
# indexing 

for i in range(5) :
    print(a[i] + b[i])

# To avoid THIS : USE NUMPY

10.1
20.2
30.3
40.4
50.5


In [ ]:
# Array : It is ordered collection of elements.

a = [10, 20, 30, 40, 50]
b = [.1, .2, .3, .4, .5]

In [ ]:
# convert sequence into array

# 1. array()

arr1 = nm.array(a)
arr2 = nm.array(b)

In [ ]:
print(arr1, type(arr1))
print(arr2, type(arr2))

[10 20 30 40 50] <class 'numpy.ndarray'>
[0.1 0.2 0.3 0.4 0.5] <class 'numpy.ndarray'>


In [ ]:
# Arithmatic Operations :

In [ ]:
# Addition :

add = arr1 + arr2
print(add)

[10.1 20.2 30.3 40.4 50.5]


In [ ]:
# Subtraction :

sub = arr1 - arr2
print(sub)

[ 9.9 19.8 29.7 39.6 49.5]


In [ ]:
# Multiplication 

mult = arr1 * arr2
print(mult)

[ 1.  4.  9. 16. 25.]


In [ ]:
# Division 

div = arr1 / arr2
print(div)

[100. 100. 100. 100. 100.]


In [ ]:
# floor Division (//)

fdiv = arr1 // arr2
print(fdiv)

[ 99.  99. 100.  99. 100.]


In [ ]:
# mod % (remainder)

mod = arr1 % arr2
print(mod)

[1.00000000e-01 2.00000000e-01 1.11022302e-15 4.00000000e-01
 0.00000000e+00]


In [ ]:
# exp (**)

pow = arr1 ** arr2
print(pow)

[1.25892541 1.8205642  2.77419111 4.3734483  7.07106781]


In [ ]:
# 2. Indexing / Slicing :

In [ ]:
c = [10, 20, 30, 40, 50, 0.1, 0.2, 0.3, 0.4, 0.5]    # List

# convert list into array

arr3 = nm.array(c)
arr3

array([10. , 20. , 30. , 40. , 50. ,  0.1,  0.2,  0.3,  0.4,  0.5])

In [ ]:
# To ascess elements : Indexing : 1. Positive 0     2. Negative -1

# Display : 20, 40, 50, 0.3, 0.5

print(arr3[1],arr3[-9] )
print(arr3[3],arr3[-7] )
print(arr3[4],arr3[-6] )
print(arr3[7],arr3[-3] )
print(arr3[9],arr3[-1] )

20.0 20.0
40.0 40.0
50.0 50.0
0.3 0.3
0.5 0.5


In [ ]:
# Slicing : array_name[start=0 : end=-1 : steps=1]

# array([10. , 20. , 30. , 40. , 50. ,  0.1,  0.2,  0.3,  0.4,  0.5])
# Display :
# 1. [10, 20, 30, 40, 50]
# 2. [0.3, 0.4, 0.5]
# 3. [10, 20, 30, 40, 50, 0.1, 0.2, 0.3, 0.4]
# 4. [10, , 40,  0.2,  0.5]

print(arr3[ : 5])
print(arr3[-3 :])
print(arr3[0 :9 ])
print(arr3[0 :  : 3])

[10. 20. 30. 40. 50.]
[0.3 0.4 0.5]
[10.  20.  30.  40.  50.   0.1  0.2  0.3  0.4]
[10.  40.   0.2  0.5]


In [ ]:
# 2 - D Array : Matrix    Rows , Columns

a = [10,20,30]
b = [40,50,60]
c = [70,80,90]
d = [70,80,90]

arr4 = nm.array([a,b,c,d])

In [ ]:
print(arr4, type(arr4))

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [70 80 90]] <class 'numpy.ndarray'>


In [ ]:
# attributes : dimensions : ndim, size : size, shape : shape

# dimensions : dim
print(arr4.ndim)

2


In [ ]:
# size 
print(arr4.size)

12


In [ ]:
# shape
print(arr4.shape)      

(4, 3)


In [ ]:
# Accessing elements :

print(arr4[0])
print(arr4[0,0])
print(arr4[0,1])
print(arr4[0,2])

[10 20 30]
10
20
30


In [ ]:
# display : 50, 70, 90

print(arr4[1,1])
print(arr4[2,0])
print(arr4[2,2])

50
70
90


In [ ]:
# create a 5, 7 matrix

arr5 = nm.array([range(1,8),range(11,18),range(21,28),range(31,38),range(41,48) ])

arr5

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15, 16, 17],
       [21, 22, 23, 24, 25, 26, 27],
       [31, 32, 33, 34, 35, 36, 37],
       [41, 42, 43, 44, 45, 46, 47]])

In [ ]:
# attributes :

print(arr5.ndim)
print(arr5.size)
print(arr5.shape)

2
35
(5, 7)


In [ ]:
# Display :
# 1. [1,  2,  3,  4]
# 2. [13, 14, 15, 16, 17]
# 3. [42, 43, 44, 45, 46]

print(arr5[0, 0:4])    # To select columns we did slicing 

[1 2 3 4]


In [ ]:
print(arr5[1, 2:])

[13 14 15 16 17]


In [ ]:
print(arr5[4, 1:6])

[42 43 44 45 46]


In [ ]:
# Display Column Values : 1 to 21

print(arr5[ 0:3 , 0])

[ 1 11 21]


In [ ]:
# Display
#                13, 14, 15, 
#                23, 24, 25, 
#                33, 34, 35,

print(arr5[ 1:4   ,  2 : 5 ])   # here, (1:4) is used to select the rows and (1:5) is used to select the columns. 

[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [ ]:
'''
  0    [ 1,  2,  3,  4,  5,  6,  7],
       
  2     [21, 22, 23, 24, 25, 26, 27],
      
  4     [41, 42, 43, 44, 45, 46, 47]
       
'''   
#  here, [0:5:2] = [start, stop, step], : = columns
print(arr5[0 : 5 : 2    ,  : ])

[[ 1  2  3  4  5  6  7]
 [21 22 23 24 25 26 27]
 [41 42 43 44 45 46 47]]


### 3 D Array :

In [ ]:
# 3 X 3 Color Image 
'''

12  15  17                 45   56   67                    100  102  103                  0      
21  34  12                 44   76   89                    121  133  145                  1
23  33  13                 54   67   78                    143  134  122                  2

Rows Columns Table

'''

# create a 3D array :

arr6 = nm.array([[[12, 15, 17], [21,34,12], [23, 33,13]],
                 [[45,56, 67], [44,76,89], [54,67,78]], 
                 [[100,102,103], [121,133,145], [143,134,122]]])

In [ ]:
# arr6
print(" Minimum value of arr1 :", arr6.max())


 Minimum value of arr1 : 145


In [ ]:
# attributes :

print(arr6.ndim)
print(arr6.size)
print(arr6.shape)       # z, x, y

3
27
(3, 3, 3)


In [ ]:
# Indexing :

# display : 100 , 76, 134, 33
print(arr6[2,0,0])
print(arr6[1,1,1])
print(arr6[2,2,1])
print(arr6[0,2,1])

100
76
134
33


In [ ]:
# slicing :


In [ ]:
'''Dsiplay : 

[45,  56,  67]
[ 44,  76,  89]

'''
print(arr6[1, :2 , ])


[[45 56 67]
 [44 76 89]]


####  Arithmatic Functions : min() , max(), sum()

In [ ]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)


[10 20 30 40 50]
[0.1 0.2 0.3 0.4 0.5]
[10.  20.  30.  40.  50.   0.1  0.2  0.3  0.4  0.5]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[ 1  2  3  4  5  6  7]
 [11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]
 [41 42 43 44 45 46 47]]
[[[ 12  15  17]
  [ 21  34  12]
  [ 23  33  13]]

 [[ 45  56  67]
  [ 44  76  89]
  [ 54  67  78]]

 [[100 102 103]
  [121 133 145]
  [143 134 122]]]


In [ ]:
# min() : returns minimum value

print(" Minimum value of arr1 :", arr1.min())
print(" Minimum value of arr2 :", arr2.min())
print(" Minimum value of arr3 :", arr3.min())

 Minimum value of arr1 : 10
 Minimum value of arr2 : 0.1
 Minimum value of arr3 : 0.1


In [ ]:
# max() : return maximum value

print(" Maximum value of arr1 :", arr1.max())
print(" Maximum value of arr2 :", arr2.max())
print(" Maximum value of arr3 :", arr3.max())

 Maximum value of arr1 : 50
 Maximum value of arr2 : 0.5
 Maximum value of arr3 : 50.0


In [ ]:
# sum()

print(" Sum of arr1 :", arr1.sum())
print(" Sum of arr2 :", arr2.sum())
print(" Sum of arr3 :", arr3.sum())

 Sum of arr1 : 150
 Sum of arr2 : 1.5
 Sum of arr3 : 151.5


In [ ]:
# Note : Columns : axis = 0               Rows : axis = 1

In [ ]:
arr7 = nm.array([[11,22,33,44], [-10, -50, 60, 70], [15, 67, -89, 54]])
arr7

array([[ 11,  22,  33,  44],
       [-10, -50,  60,  70],
       [ 15,  67, -89,  54]])

In [ ]:
# Display row wise min values 

print(arr7.min(axis = 1))

[ 11 -50 -89]


In [ ]:
# Display row wise max values 

print(arr7.max(axis = 1))

[44 70 67]


In [ ]:
# Display row wise sum

print(arr7.sum(axis = 1))

[110  70  47]


In [ ]:
# Display column wise min values 

print(arr7.min(axis = 0))

[-10 -50 -89  44]


In [ ]:
# Display column wise max values 

print(arr7.max(axis = 0))

[15 67 60 70]


In [ ]:
# Display column wise sum

print(arr7.sum(axis = 0))

[ 16  39   4 168]


In [ ]:
# min() max() sum() + rows : '1', columns : '0'   + index/slicing 

In [ ]:
# Find main value in 3rd row.

print(arr7.min(axis = 1)[2])

-89


In [ ]:
# Find max value in 2nd column

print(arr7.max(0)[1])

67


In [ ]:
# Find sum of all elements of 1st row.

print(arr7.sum(1)[0])


110


In [ ]:
# reshape()

arr7 = nm.array([[11,22,33,44], [-10, -50, 60, 70], [15, 67, -89, 54]])

print(arr7)
print(" Dimensions : {} \t Size : {} \t Shape : {}".format(arr7.ndim, arr7.size, arr7.shape ))

# row = 3    columns = 4         =>     row = 2   column = 6

arr8 = arr7.reshape(2,6)
print(arr8)
print(" Dimensions : {} \t Size : {} \t Shape : {}".format(arr8.ndim, arr8.size, arr8.shape ))

[[ 11  22  33  44]
 [-10 -50  60  70]
 [ 15  67 -89  54]]
 Dimensions : 2 	 Size : 12 	 Shape : (3, 4)
[[ 11  22  33  44 -10 -50]
 [ 60  70  15  67 -89  54]]
 Dimensions : 2 	 Size : 12 	 Shape : (2, 6)


In [ ]:
import numpy as nm

In [ ]:
# python : range(start , end, steps )

# create 1 to 100.

a = range(1, 101 )

In [ ]:
print(tuple(a))

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100)


In [ ]:
print(list(a))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [ ]:
# Sequence Generators : arange() linspace()

In [ ]:
# 1. arange(start , end, steps )

b = nm.arange(1,101)
print(b)

print(type(b))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
<class 'numpy.ndarray'>


In [ ]:
# 2. linspace(start , end, interval)

c = nm.linspace(1,10, 5)
print(c)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
9/4


2.25

In [ ]:
1 + 2.25 + 2.25 +2.25 + 2.25

10.0

In [ ]:
m1 = nm.array([range(1,6), range(11,16),range(21,26), range(31,36), range(41,46), range(51,56), range(61,66)])
m1

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55],
       [61, 62, 63, 64, 65]])

In [ ]:
print(m1.ndim, m1.shape, m1.size)

2 (7, 5) 35


In [ ]:
print(m1)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]
 [61 62 63 64 65]]


In [ ]:
# 2. Find Max number from 3,4,5 columns

print(m1.max(0)[2 : ])                    # slicing after function

print(m1[ : ,  2 : ].max(0))              # slicing before function

[63 64 65]
[63 64 65]


In [ ]:
# 3. Find sum of 5th column.

print(m1.sum(0)[-1])

245


In [ ]:
# 4. Find Min value from 6 th row.

print(m1.min(1)[5])

51


#### Troginometric Functions

In [ ]:
# sin, cos, tan

angles_degree = nm.array([0 , 30, 45, 60, 90, 180])
angles_radians = (nm.pi / 180) * angles_degree

In [ ]:
# Trigonometric sin

a_sin = nm.sin(angles_radians)
print(a_sin)

# Trigonometric cos

a_cos = nm.cos(angles_radians)
print(a_cos)

# Trigonometric tan

a_tan = nm.tan(angles_radians)
print(a_tan)


[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]
[ 1.00000000e+00  8.66025404e-01  7.07106781e-01  5.00000000e-01
  6.12323400e-17 -1.00000000e+00]
[ 0.00000000e+00  5.77350269e-01  1.00000000e+00  1.73205081e+00
  1.63312394e+16 -1.22464680e-16]


###### floor() : removes all decimal points
###### ceil()  :  returns to next nearest integer
###### around() : 

In [ ]:
arr1 = nm.linspace(1,5, 7)
print(arr1)

[1.         1.66666667 2.33333333 3.         3.66666667 4.33333333
 5.        ]


In [ ]:
print("Output of Floor : ", nm.floor(arr1))
print("Output of ceil : ", nm.ceil(arr1))
print("Output of Around : ", nm.around(arr1, 3))

Output of Floor :  [1. 1. 2. 3. 3. 4. 5.]
Output of ceil :  [1. 2. 3. 3. 4. 5. 5.]
Output of Around :  [1.    1.667 2.333 3.    3.667 4.333 5.   ]


####  Statistical Functions : 

In [ ]:
# mean() , median()

arr2 = nm.array([2,4,10,46,54,5,7,643,24,11,76,54,43,4,57,65,3,6,76,543,4,57,65,44,6,5,4,4,6,56,4,6,65,4,57,6,76,5,45,4], order = 'F')

print(" Mean of arr2 : ", nm.floor(nm.mean(arr2)))

print("Median of arr2 : ", nm.median(arr2))

 Mean of arr2 :  56.0
Median of arr2 :  10.5


##### Generate random values

In [ ]:
nm.random.randint(1, 10, 5)  # start value, stop value, total random numbers required

array([3, 3, 1, 7, 6])

In [ ]:
# Create a 50 X 3 Matrix.    Rows : 50, columns : 3
# Mean of each column.
# median of each column.

In [ ]:
arr2 = nm.array([nm.random.randint(21, 50, 50), nm.random.randint(25, 50, 50), nm.random.randint(11, 50, 50)]).reshape(50,3)
arr2

In [ ]:
arr2.shape

(50, 3)

In [ ]:
arr2.mean(0)

array([33.48, 34.2 , 31.46])

In [ ]:
print("Median of Col1 : {} \t Median of Col2 : {} \t Median of Col3 : {}".format(nm.median(arr2[0]),nm.median(arr2[1]),nm.median(arr2[2])))

Median of Col1 : 31.0 	 Median of Col2 : 31.0 	 Median of Col3 : 33.0


In [ ]:
import numpy as nm
import numpy.matlib

In [ ]:
# Matrix : 

# empty() : Creating empty matrix 

# 1. Create a 5X5 empty matrix

a = numpy.matlib.empty((5,5))
print(a)

[[ 2.15583213e-316  0.00000000e+000  0.00000000e+000 -1.00000000e+000
   1.00000000e+000]
 [-2.00000000e+000  2.00000000e+000 -1.00000000e+000  1.00000000e+000
   0.00000000e+000]
 [ 2.00000000e+000  1.00000000e+000  1.00000000e+000  2.00000000e+000
   0.00000000e+000]
 [ 1.00000000e+000 -1.00000000e+000  2.00000000e+000 -2.00000000e+000
   1.00000000e+000]
 [-1.00000000e+000  0.00000000e+000 -2.00000000e+000 -1.00000000e+000
   1.02765654e-321]]


In [ ]:
# 2. Create a 3X2 empty matrix

b = numpy.matlib.empty((3,2))
print(b)

[[ 0.00000000e+00  5.77350269e-01]
 [ 1.00000000e+00  1.73205081e+00]
 [ 1.63312394e+16 -1.22464680e-16]]


In [ ]:
# zeros() : create a matrix of zeros.

# 1. create a matrix of 5X5.

a = numpy.matlib.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# ones() : create a matrix of ones.

# 1. create a matrix of 5X3.

b = numpy.matlib.ones((5,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# identity() : create an Identity matrix.

c = numpy.matlib.identity(6)
print(c)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Matrix Multiplication :

1 2 3       10 20 30                    25    36    58
4 5 6        6  5  8       
7 8 9        1  2  4

c(1,1)= (1*10 + 2*6 + 3*1 ) = 10 +12 +3 = 25
c(1,2)= (1*20 + 2*5 + 3*2 ) = 20 + 10 + 6 = 36
c(1,3)= (1*30 + 2*8 + 3*4 ) = 30 + 16 + 12 = 58

In [ ]:
# Matrix Multiplication : 

# matmul() :

a = nm.array([[1,2,3], [4,5,6], [7,8,9]])
b = nm.array([[10,20,30], [6,5,8], [1,2,4]])

print(a)
print(b)

c = nm.matmul(a,b)

print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [ 6  5  8]
 [ 1  2  4]]
[[ 25  36  58]
 [ 76 117 184]
 [127 198 310]]


In [ ]:
# multiply()  : Element wise multiplication 

d = nm.multiply(a,b)

print(d)

[[10 40 90]
 [24 25 48]
 [ 7 16 36]]


In [ ]:
# vector :
# 1. dot() : dot product

a = nm.array([1,2,3,4,5])
b = nm.array([10,20,30,40,50])

#dot_product = a1* b1 + a2+b2 + a3*b3 + ... = 1*10 + 2*20 + 3*30 + 4*40 + 5 * 50 = 10+40 + 90+160+250 = 550

c = nm.dot(a,b)
print(c)

550


In [ ]:
# Determinant of Matrix : det() 

a = nm.array([[1,2], [3,4]])

# 1   2
# 3   4     = (1 * 4) - (2 * 3) = 4-6 = -2


det = nm.linalg.det(a)
print("Determinant of Matrix : ",det)

Determinant of Matrix :  -2.0000000000000004


In [ ]:
# Inverse of a Matrix : inv()

# 1. determinant        2. co-factors        3. Inverse

# A * [INV]  = [1]


a = nm.array([[1,2], [3,4]])

inv = nm.linalg.inv(a)
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
nm.around(nm.matmul(a, inv),1)

array([[1., 0.],
       [0., 1.]])

In [ ]:
a = nm.array([10,20,30,40,50],dtype= bool)

In [ ]:
a

array([ True,  True,  True,  True,  True])